### ISSUE TITLE
The code has references to local paths

### ISSUE THREAD

**Issue by raydelto** [gcaff/mapaRD#1]
On the following line of code we can find a reference to a local path which would not allow this code to be run on any computer other than the one used by the repo creator:

We can find an example of this on the generar_mapas.R file where the following local path can be found:

```~/Documents/PascalAnalytics/proyectos/MapaPoliticoRD/mapa```

https://github.com/gcaff/mapaRD/blob/7fb770d47a6eeb059be28faa341a1a49d0522adf/R/generar_mapas.R#L14

**Comment by gcaff** [comment]
The file generar_mapas.R was used to generate the initial map data. It was removed from the repository.
Thank you!
